### PR TITLE
Users should be able to search for dive sites

### PR DESCRIPTION
**Pull request by blakes24**
### What does this PR do?
- This PR allows users to search for dive sites
### Description of Task to be completed
- A user picks a point on the map or enters a term in the search bar to find dive sites
### How should this be manually tested?
- Go to the home page 
- Type something in the search bar and submit
- Drop a pin on the map then click the search map button

### CODE REVIEW

**Comment by blakes24** [comment]
I have set it up so the token doesn't get pushed to GitHub for now, but I know this won't work for production. Maybe I can make that a separate pull request since I'm struggling to figure it out. That way I can at least make progress with other features while I'm getting that worked out. Would that work?

**Comment by alexkayabula** [comment]
Hey Blakely,
I hope you are doing well. Sorry for the late reply, I had been a bit tied
up. I am ok with that, you can proceed.

Regards,

Alex

**Comment by alexkayabula** [comment]
@blakes24 kindly resolve the merge conflicts.

**Comment by blakes24** [comment]
The merge conflicts have been resolved. Sorry it's been a while. I've been a bit busy lately.

**Comment by alexkayabula** [comment]
LGTM

**Pull request merged**
