### PR TITLE
Improve mobile UX/UI

### PR DESCRIPTION
**Pull request by blakes24**
### What does this PR do?
- This PR improves UX/UI for mobile use

### CODE REVIEW

**Comment by blakes24** [comment]
Removed search/pin changes

**Review by alexkayabula — APPROVED** [review]
Thank you.

**Comment by alexkayabula** [comment]
@blakes24 kindly fix the merge conflicts.

**Comment by blakes24** [comment]
@alexkayabula merge conflicts are fixed

**Pull request merged**
