### PR TITLE
Improve project structure and CI/CD build when automatic database table setup is configured

### LINKED ISSUE #19: Database and database tables creation when you run application
When running the application, i.e `flask run`, It would be a good idea to have the database and related tables created automatically if they don't exist.

### PR DESCRIPTION
**Pull request by blakes24**
### What does this PR do?
- This PR Improves project structure and CI/CD build when automatic database table setup is configured.
- Fixes #19  

### Tasks
- [x] Restructure project set up.
- [x] Setup application environments i.e Production, Testing, Development.
- [x] Implement automatic creation of database tables.
- [x] Improve test configuration.
- [x] Update documentation.

### CODE REVIEW

**Comment by alexkayabula** [comment]
@blakes24 kindly specify what help is needed for this pull request.

**Comment by blakes24** [comment]
When I use `db.creat_all()` to create my tables if they don't already exist, it works fine on my computer. I am also able to run my tests without issue and they all pass. But when I push to GitHub my Travis builds are failing with `ImportError: Failed to import test module: test_models` (same error for `test_views`). 
I've tried tweaking the code for the tests and for adding tables but each time it works on my computer but fails in Travis CI. Do you have any suggestions?

**Comment by alexkayabula** [comment]
@blakes24 kindly review in detail and thoroughly test out the changes in this pull request. Reply to this thread if you have any questions or if everything looks ok so that I can merge.

**Comment by blakes24** [comment]
@alexkayabula Looks good. Thank you for your help. The only issue is there are two CSS files and the one inside app/static is blank so the styles aren't showing up. Do you want me to move the correct file into the app folder and delete the extra static folder?

**Comment by alexkayabula** [comment]
> @alexkayabula Looks good. Thank you for your help. The only issue is there are two CSS files and the one inside app/static is blank so the styles aren't showing up. Do you want me to move the correct file into the app folder and delete the extra static folder?

It is ok you can move it.

**Comment by blakes24** [comment]
CSS file fixed

**Review by alexkayabula — APPROVED** [review]
LGTM

**Pull request merged**
