### PR TITLE
User should be able to delete their profile

### PR DESCRIPTION
**Pull request by blakes24**
### What does this PR do?
- This PR allows users to delete their profile
### Description of Task to be completed
- Users should be able to delete their own profile
### How should this be manually tested?
- Clone the repository
- log in
- go to `localhost:5000/user/edit`
- click delete profile

### CODE REVIEW

**Review by alexkayabula — CHANGES_REQUESTED** [review]
This feature is not working as expected. Kindly test out this feature
Screen Shot 2021-01-06 at 10 05 28 AM

**Comment by blakes24** [comment]
The feature is working fine for me. The only way I can reproduce the issue is if I manually type in `localhost:5000/user/delete` instead of using the button, which isn't supposed to work because it is only a POST route. I'm not sure how to fix it if I can't reproduce the error. What should I do?

**Comment by alexkayabula** [comment]
> The feature is working fine for me. The only way I can reproduce the issue is if I manually type in `localhost:5000/user/delete` instead of using the button, which isn't supposed to work because it is only a POST route. I'm not sure how to fix it if I can't reproduce the error. What should I do?

I don't seem to understand the statement above. Kindly shade more light on the questions below.

`1. What steps does an end user have to follow to delete their profile ?`
`2. When a user follows the steps above, Are they able to delete their profile ?`
`3. What part of the implemented functionality doesn't work ?`
`4. What error can't you reproduce ?`

If a user follows the instructions below, they will not be able to delete their profile.

`1. User logins in `
`2. User clicks on their profile name to edit.`
`3. User clicks the delete profile button.`
`4. User profile is not deleted`

**Comment by blakes24** [comment]
> If a user follows the instructions below, they will not be able to delete their profile.
> 
> `1. User logins in `
> `2. User clicks on their profile name to edit.`
> `3. User clicks the delete profile button.`
> `4. User profile is not deleted`

The issue is that when I follow these steps the feature works, the user profile is deleted. When I run my tests they pass. I don't know how to fix the problem because I can't replicate it.

Screen Shot 2021-01-06 at 8 32 33 AM

**Comment by alexkayabula** [comment]
@blakes24 my bad....Sorry I was testing it out in a different branch.

**Review by alexkayabula — APPROVED** [review]
LGTM

**Pull request merged**
