### PR TITLE
Add Coveralls to check code coverage

### PR DESCRIPTION
**Pull request by blakes24**
### What does this PR do?
- This PR adds Coveralls to the repository to check code test coverage

### CODE REVIEW

**Comment by alexkayabula** [comment]
@blakes24 add a coveralls coverage badge to the READMe.md

**Comment by blakes24** [comment]
Badge added.

**Comment by alexkayabula** [comment]
@blakes24 please align the COVERALLS badge on the same line as the code quality badge.
Screen Shot 2020-12-10 at 9 24 50 AM

**Comment by blakes24** [comment]
Badges moved to the same line.

**Pull request merged**
