### PR TITLE
Improve search functionality

### PR DESCRIPTION
**Pull request by blakes24**
### What does this PR do?
- This PR improves search functionality
### Description of Task to be completed
- Touch and hold to add a pin to the map on mobile
- Use the same button for location and text-based searches
- Show/hide a list view of the search results
### How should this be manually tested?
- Run `run.py`
- Go to `localhost:5000`
- Search for dive sites

### CODE REVIEW

**Review by alexkayabula — COMMENTED** [review]
@blakes24 I am unable to load the map. Kindly check it out.

**Comment by blakes24** [comment]
I have URL restrictions set on my mapbox token so that maps will only load on the site deployed on heroku, but it is working fine when I test it on my computer. It is still possible to test out the functionality even though you can't see the map.

**Comment by alexkayabula** [comment]
Ok let me do that

**Comment by alexkayabula** [comment]
LGTM

**Pull request merged**
